apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: olxi5u1c7-dotnet-basic
  janus-idp.io/tekton: olxi5u1c7-dotnet-basic
  backstage.io/kubernetes-id: olxi5u1c7-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: olxi5u1c7-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
